//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoenaSoft.DVDProfiler.EnhancedFeatures.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoenaSoft.DVDProfiler.EnhancedFeatures.Resources.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        internal static string Basics {
            get {
                return ResourceManager.GetString("Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BD-Live.
        /// </summary>
        internal static string BDLive {
            get {
                return ResourceManager.GetString("BDLive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Trailer.
        /// </summary>
        internal static string BonusTrailer {
            get {
                return ResourceManager.GetString("BonusTrailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for Updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CineChat.
        /// </summary>
        internal static string CineChat {
            get {
                return ResourceManager.GetString("CineChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Captioned.
        /// </summary>
        internal static string ClosedCaptioned {
            get {
                return ResourceManager.GetString("ClosedCaptioned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentary.
        /// </summary>
        internal static string Commentary {
            get {
                return ResourceManager.GetString("Commentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy all data to clipboard.
        /// </summary>
        internal static string CopyAllToClipboard {
            get {
                return ResourceManager.GetString("CopyAllToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D-Box.
        /// </summary>
        internal static string DBox {
            get {
                return ResourceManager.GetString("DBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Scenes.
        /// </summary>
        internal static string DeletedScenes {
            get {
                return ResourceManager.GetString("DeletedScenes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digital Copy.
        /// </summary>
        internal static string DigitalCopy {
            get {
                return ResourceManager.GetString("DigitalCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DVD-ROM Content.
        /// </summary>
        internal static string DVDROMContent {
            get {
                return ResourceManager.GetString("DVDROMContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edition.
        /// </summary>
        internal static string Edition {
            get {
                return ResourceManager.GetString("Edition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Features.
        /// </summary>
        internal static string EF {
            get {
                return ResourceManager.GetString("EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excel Columns.
        /// </summary>
        internal static string ExcelColumns {
            get {
                return ResourceManager.GetString("ExcelColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Options.
        /// </summary>
        internal static string ExportOptions {
            get {
                return ResourceManager.GetString("ExportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Collection.xml.
        /// </summary>
        internal static string ExportToCollectionXml {
            get {
                return ResourceManager.GetString("ExportToCollectionXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to Excel.
        /// </summary>
        internal static string ExportToExcel {
            get {
                return ResourceManager.GetString("ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XML.
        /// </summary>
        internal static string ExportToXml {
            get {
                return ResourceManager.GetString("ExportToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature.
        /// </summary>
        internal static string Feature {
            get {
                return ResourceManager.GetString("Feature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Ending(s).
        /// </summary>
        internal static string Feature1 {
            get {
                return ResourceManager.GetString("Feature1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Test.
        /// </summary>
        internal static string Feature10 {
            get {
                return ResourceManager.GetString("Feature10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season Play.
        /// </summary>
        internal static string Feature11 {
            get {
                return ResourceManager.GetString("Feature11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorts.
        /// </summary>
        internal static string Feature12 {
            get {
                return ResourceManager.GetString("Feature12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sing-Alongs.
        /// </summary>
        internal static string Feature13 {
            get {
                return ResourceManager.GetString("Feature13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storybook.
        /// </summary>
        internal static string Feature14 {
            get {
                return ResourceManager.GetString("Feature14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trivia Tracks.
        /// </summary>
        internal static string Feature15 {
            get {
                return ResourceManager.GetString("Feature15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnable Cover.
        /// </summary>
        internal static string Feature16 {
            get {
                return ResourceManager.GetString("Feature16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U-Control.
        /// </summary>
        internal static string Feature17 {
            get {
                return ResourceManager.GetString("Feature17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Links.
        /// </summary>
        internal static string Feature18 {
            get {
                return ResourceManager.GetString("Feature18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webisodes.
        /// </summary>
        internal static string Feature19 {
            get {
                return ResourceManager.GetString("Feature19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art Sketches.
        /// </summary>
        internal static string Feature2 {
            get {
                return ResourceManager.GetString("Feature2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 20.
        /// </summary>
        internal static string Feature20 {
            get {
                return ResourceManager.GetString("Feature20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 21.
        /// </summary>
        internal static string Feature21 {
            get {
                return ResourceManager.GetString("Feature21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 22.
        /// </summary>
        internal static string Feature22 {
            get {
                return ResourceManager.GetString("Feature22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 23.
        /// </summary>
        internal static string Feature23 {
            get {
                return ResourceManager.GetString("Feature23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 24.
        /// </summary>
        internal static string Feature24 {
            get {
                return ResourceManager.GetString("Feature24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 25.
        /// </summary>
        internal static string Feature25 {
            get {
                return ResourceManager.GetString("Feature25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 26.
        /// </summary>
        internal static string Feature26 {
            get {
                return ResourceManager.GetString("Feature26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 27.
        /// </summary>
        internal static string Feature27 {
            get {
                return ResourceManager.GetString("Feature27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 28.
        /// </summary>
        internal static string Feature28 {
            get {
                return ResourceManager.GetString("Feature28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 29.
        /// </summary>
        internal static string Feature29 {
            get {
                return ResourceManager.GetString("Feature29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus CD.
        /// </summary>
        internal static string Feature3 {
            get {
                return ResourceManager.GetString("Feature3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 30.
        /// </summary>
        internal static string Feature30 {
            get {
                return ResourceManager.GetString("Feature30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 31.
        /// </summary>
        internal static string Feature31 {
            get {
                return ResourceManager.GetString("Feature31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 32.
        /// </summary>
        internal static string Feature32 {
            get {
                return ResourceManager.GetString("Feature32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 33.
        /// </summary>
        internal static string Feature33 {
            get {
                return ResourceManager.GetString("Feature33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 34.
        /// </summary>
        internal static string Feature34 {
            get {
                return ResourceManager.GetString("Feature34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 35.
        /// </summary>
        internal static string Feature35 {
            get {
                return ResourceManager.GetString("Feature35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 36.
        /// </summary>
        internal static string Feature36 {
            get {
                return ResourceManager.GetString("Feature36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 37.
        /// </summary>
        internal static string Feature37 {
            get {
                return ResourceManager.GetString("Feature37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 38.
        /// </summary>
        internal static string Feature38 {
            get {
                return ResourceManager.GetString("Feature38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 39.
        /// </summary>
        internal static string Feature39 {
            get {
                return ResourceManager.GetString("Feature39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Episodes.
        /// </summary>
        internal static string Feature4 {
            get {
                return ResourceManager.GetString("Feature4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature 40.
        /// </summary>
        internal static string Feature40 {
            get {
                return ResourceManager.GetString("Feature40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booklet.
        /// </summary>
        internal static string Feature5 {
            get {
                return ResourceManager.GetString("Feature5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate of Authenticity.
        /// </summary>
        internal static string Feature6 {
            get {
                return ResourceManager.GetString("Feature6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gag Reel.
        /// </summary>
        internal static string Feature7 {
            get {
                return ResourceManager.GetString("Feature7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mini Poster.
        /// </summary>
        internal static string Feature8 {
            get {
                return ResourceManager.GetString("Feature8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Before Seen Footage.
        /// </summary>
        internal static string Feature9 {
            get {
                return ResourceManager.GetString("Feature9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features.
        /// </summary>
        internal static string Features {
            get {
                return ResourceManager.GetString("Features", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Trailers.
        /// </summary>
        internal static string FeatureTrailers {
            get {
                return ResourceManager.GetString("FeatureTrailers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featurettes.
        /// </summary>
        internal static string Featurettes {
            get {
                return ResourceManager.GetString("Featurettes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount of Filters.
        /// </summary>
        internal static string FilterCount {
            get {
                return ResourceManager.GetString("FilterCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from XML.
        /// </summary>
        internal static string ImportFromXml {
            get {
                return ResourceManager.GetString("ImportFromXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Options.
        /// </summary>
        internal static string ImportOptions {
            get {
                return ResourceManager.GetString("ImportOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Games.
        /// </summary>
        internal static string InteractiveGames {
            get {
                return ResourceManager.GetString("InteractiveGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interviews.
        /// </summary>
        internal static string Interviews {
            get {
                return ResourceManager.GetString("Interviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invelos Data.
        /// </summary>
        internal static string InvelosData {
            get {
                return ResourceManager.GetString("InvelosData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string Labels {
            get {
                return ResourceManager.GetString("Labels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Enhanced Features from XML.
        /// </summary>
        internal static string LoadXmlFile {
            get {
                return ResourceManager.GetString("LoadXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misc..
        /// </summary>
        internal static string Misc {
            get {
                return ResourceManager.GetString("Misc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MovieIQ.
        /// </summary>
        internal static string MovieIQ {
            get {
                return ResourceManager.GetString("MovieIQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi-angle.
        /// </summary>
        internal static string MultiAngle {
            get {
                return ResourceManager.GetString("MultiAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Videos.
        /// </summary>
        internal static string MusicVideos {
            get {
                return ResourceManager.GetString("MusicVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original Title.
        /// </summary>
        internal static string OriginalTitle {
            get {
                return ResourceManager.GetString("OriginalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outtakes / Bloopers.
        /// </summary>
        internal static string OuttakesBloopers {
            get {
                return ResourceManager.GetString("OuttakesBloopers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste all data from clipboard.
        /// </summary>
        internal static string PasteAllFromClipboard {
            get {
                return ResourceManager.GetString("PasteAllFromClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture-in-picture.
        /// </summary>
        internal static string PictureInPicture {
            get {
                return ResourceManager.GetString("PictureInPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play All.
        /// </summary>
        internal static string PlayAll {
            get {
                return ResourceManager.GetString("PlayAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Data.
        /// </summary>
        internal static string PluginData {
            get {
                return ResourceManager.GetString("PluginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to add more user-defined features to a profile..
        /// </summary>
        internal static string PluginDescription {
            get {
                return ResourceManager.GetString("PluginDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enhanced Features.
        /// </summary>
        internal static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://doena-journal.net/en/dvd-profiler-tools/.
        /// </summary>
        internal static string PluginUrl {
            get {
                return ResourceManager.GetString("PluginUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Notes / Bios.
        /// </summary>
        internal static string ProductionNotesBios {
            get {
                return ResourceManager.GetString("ProductionNotesBios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Enhanced Features to XML.
        /// </summary>
        internal static string SaveXmlFile {
            get {
                return ResourceManager.GetString("SaveXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scene Access.
        /// </summary>
        internal static string SceneAccess {
            get {
                return ResourceManager.GetString("SceneAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Title.
        /// </summary>
        internal static string SortTitle {
            get {
                return ResourceManager.GetString("SortTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storyboard Comparisons.
        /// </summary>
        internal static string StoryboardComparisons {
            get {
                return ResourceManager.GetString("StoryboardComparisons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THX Certified.
        /// </summary>
        internal static string THXCertified {
            get {
                return ResourceManager.GetString("THXCertified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI Language.
        /// </summary>
        internal static string UiLanguage {
            get {
                return ResourceManager.GetString("UiLanguage", resourceCulture);
            }
        }
    }
}
